# baseURL = 'https://example.org/'
# languageCode = 'en-us'
# title = 'My New Hugo Site'

baseURL = 'https://ApiwatWis.github.io/BangmodFusionHub/'
languageCode = 'th'
title = 'BangmodFusionHub'
theme = 'hugo-book'

# Enable Math (LaTeX) support for physics equations
[params]
  BookTheme = 'light'
  # This enables the formula rendering $$ ... $$
  BookMath = true 
  BookLogo = 'images/logo-without-text.png' 

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true # Needed for some complex math/html rendering